language: java
jdk: oraclejdk7

branches:
    only:
        - dev
        - master

before_install:
    # Install base Android SDK
    - sudo apt-get update -qq; sudo apt-get install -qq libstdc++6:i386 lib32z1
    - export COMPONENTS=build-tools-19.0.3,android-19,sysimg-19,extra-android-support,extra-android-m2repository,extra-google-m2repository
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
    - source ~/.android-sdk-installer/env

    # Create and start emulator
    - echo no | android create avd --force --name test-avd --target android-19 --abi armeabi-v7a
    - emulator -avd test-avd -no-skin -no-audio -no-window &

before_script:
    - wait_for_emulator

script:
    - ./gradlew connectedCheck
